export enum Endpoint {
  CATEGORY = '/v0/category',
  CATEGORY_TREE = '/v0/category/tree',
  PRODUCT = '/v0/product',
  PRODUCT_REVIEW = '/v0/product/review',
  QUESTIONS = '/v0/questions',
  SLIDER = '/v0/slider',
  HOME_PRODUCTS = '/v0/product/home',
  AUTH_PHONE = '/v0/auth/phone',
  AUTH = '/v0/auth',
  CART = '/v0/cart',
  AUTH_ME = '/v0/auth/me',
  ORDERS = '/v0/order',
  TO_PAYMENT = '/v0/order/to-payment',
  BUILD_LIST = '/v0/build-list',
  CHECKOUT_BUILD = '/v0/order/builder',
}
